In [2]:
import pandas as pd

`src/process_bg_tables/util/load_csv_with_dtypes` can be used to load the .csv with the correct datatypes. (ex: `load_csv_with_dtypes('ACS_BG_DATA_2022')`)

In [1]:
import sys
sys.path.append("./src/")
from src.process_bg_tables.util import load_csv_with_dtypes
from src.configs import ACS_BG_FILENAME

In [4]:
df = load_csv_with_dtypes(ACS_BG_FILENAME, rel_path=".")

In [5]:
df.head()

,bg_fips,census_tract_fips,county_fips,state_fips,state,county_name,population,non_institutionized_pop,households,pct_hh_internet_subscription,...,pct_inst_groupquarters_2020,pct_non_inst_groupquarters_2020,zip,msa_code,MSA,tract_pop_density_sqmile,pct_tract_groupqtrs,pct_tract_military_employed,military_base_flag,military_base_flag_geo
0,010010201001,01001020100,01001,01,AL,"Autauga County, Alabama",558,558,261,0.950192,...,0.00000,0.000000,36067,C3386,"Montgomery, AL MSA",1132.736616,0.000000,0.003217,0,0
1,010010201002,01001020100,01001,01,AL,"Autauga County, Alabama",1307,1301,439,0.899772,...,0.00000,0.000000,36067,C3386,"Montgomery, AL MSA",868.606955,0.000000,0.003217,0,0
2,010010202001,01001020200,01001,01,AL,"Autauga County, Alabama",548,546,204,0.750000,...,0.00000,0.000000,36067,C3386,"Montgomery, AL MSA",2341.638433,0.098872,0.015046,0,0
3,010010202002,01001020200,01001,01,AL,"Autauga County, Alabama",1313,1103,340,0.805882,...,0.13136,0.000000,36067,C3386,"Montgomery, AL MSA",3817.965524,0.098872,0.015046,0,0
4,010010203001,01001020300,01001,01,AL,"Autauga County, Alabama",2835,2829,1011,0.928783,...,0.00589,0.002103,36067,C3386,"Montgomery, AL MSA",2339.120054,0.002005,0.007732,0,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242336 entries, 0 to 242335
Data columns (total 50 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   bg_fips                                     242336 non-null  object
 1   census_tract_fips                           242336 non-null  object
 2   county_fips                                 242336 non-null  object
 3   state_fips                                  242336 non-null  object
 4   state                                       242336 non-null  object
 5   county_name                                 242336 non-null  object
 6   population                                  242336 non-null  int32
 7   non_institutionized_pop                     242336 non-null  int32
 8   households                                  242336 non-null  int32
 9   pct_hh_internet_subscription                239535 non-null  float64
 10  pct_hh_vehicle_ownership                    239535 non-null  float64
 11  avg_vehicles_per_hh                         239535 non-null  float64
 12  pct_hh_foodstamps                           239535 non-null  float64
 13  pct_home_ownership                          239535 non-null  float64
 14  prop_female                                 240172 non-null  float64
 15  prop_age_under_18                           240172 non-null  float64
 16  prop_age_18_24                              240172 non-null  float64
 17  prop_age_18_29                              240172 non-null  float64
 18  prop_age_25_34                              240172 non-null  float64
 19  prop_age_35_44                              240172 non-null  float64
 20  prop_age_45_54                              240172 non-null  float64
 21  prop_age_50_64                              240172 non-null  float64
 22  prop_age_55_64                              240172 non-null  float64
 23  prop_age_65_69                              240172 non-null  float64
 24  prop_age_65_74                              240172 non-null  float64
 25  median_age                                  240002 non-null  float64
 26  race_pct_white                              240172 non-null  float64
 27  race_pct_african_american                   240172 non-null  float64
 28  race_pct_nativeam                           240172 non-null  float64
 29  race_pct_asian                              240172 non-null  float64
 30  race_pct_other                              242336 non-null  float64
 31  race_pct_hispanic                           240172 non-null  float64
 32  median_income                               225130 non-null  float64
 33  pct_college_enrolled                        240172 non-null  float64
 34  prop_college_educated                       240172 non-null  float64
 35  pct_married                                 240172 non-null  float64
 36  blockgroup_center_lat                       242336 non-null  float64
 37  blockgroup_center_lng                       242336 non-null  float64
 38  amindian_aknative_hawaiiannative_land_flag  242331 non-null  float64
 39  pop_density_sqmile                          242336 non-null  float64
 40  pct_inst_groupquarters_2020                 240942 non-null  float64
 41  pct_non_inst_groupquarters_2020             240942 non-null  float64
 42  zip                                         240949 non-null  object
 43  msa_code                                    224031 non-null  object
 44  MSA                                         224031 non-null  object
 45  tract_pop_density_sqmile                    241946 non-null  float64
 46  pct_tract_groupqtrs                         241401 non-null  float64
 47  pct_tract_military_employed                 241401 non-null  float64
 48  military_base_flag                          242336 non-null  int32
 49  military_base_flag_geo                      242336 non-null  int32
dtypes: float64(36), int32(5), object(9)
memory usage: 87.8+ MB