In [1]:
import sys
sys.path.append("../src/")

from process_bg_tables.util import load_csv_with_dtypes #load_checkpoint_df, process_some_cols_bg_table
from configs import ACS_BG_FILENAME
# import db_utils

import pandas as pd
pd.set_option("display.max_columns", 100)

from collections import Counter, OrderedDict

import pickle

from collections import Counter

import csv

# load data

In [2]:
REL_PATH = ".."
df = load_csv_with_dtypes(ACS_BG_FILENAME, REL_PATH)

In [3]:
df.head()

,bg_fips,census_tract_fips,county_fips,state_fips,state,county_name,population,non_institutionized_pop,households,pct_hh_internet_subscription,pct_hh_vehicle_ownership,avg_vehicles_per_hh,pct_hh_foodstamps,pct_home_ownership,pct_hh_income_up_to_10k,pct_hh_income_10k_to_15k,pct_hh_income_15k_to_20k,pct_hh_income_20k_to_25k,pct_hh_income_25k_to_30k,pct_hh_income_30k_to_35k,pct_hh_income_35k_to_40k,pct_hh_income_40k_to_45k,pct_hh_income_45k_to_50k,pct_hh_income_50k_to_60k,pct_hh_income_60k_to_75k,pct_hh_income_75k_to_100k,pct_hh_income_100k_to_125k,pct_hh_income_125k_to_150k,pct_hh_income_150k_to_200k,pct_hh_income_200k_and_above,prop_female,prop_age_under_18,prop_age_18_24,prop_age_18_29,prop_age_25_34,prop_age_35_44,prop_age_45_54,prop_age_50_64,prop_age_55_64,prop_age_65_69,prop_age_65_74,median_age,race_pct_white,race_pct_african_american,race_pct_nativeam,race_pct_asian,race_pct_other,race_pct_hispanic,median_income,pct_college_enrolled,prop_college_educated,pct_married,blockgroup_center_lat,blockgroup_center_lng,amindian_aknative_hawaiiannative_land_flag,pop_density_sqmile,pct_inst_groupquarters_2020,pct_non_inst_groupquarters_2020,zip,msa_code,MSA,tract_pop_density_sqmile,pct_tract_groupqtrs,pct_tract_military_employed,military_base_flag,military_base_flag_geo
0,010010201001,01001020100,01001,01,AL,"Autauga County, Alabama",558,558,261,0.950192,1.000000,2.256705,0.160920,0.689655,0.000000,0.095785,0.126437,0.000000,0.068966,0.049808,0.030651,0.145594,0.000000,0.053640,0.080460,0.057471,0.030651,0.007663,0.007663,0.245211,0.460573,0.161290,0.080645,0.150538,0.173835,0.050179,0.118280,0.268817,0.159498,0.100358,0.150538,50.9,0.851254,0.021505,0.0,0.00000,0.127240,0.091398,42204.0,0.089606,0.207885,0.394265,32.465926,-86.490582,0.0,338.909937,0.00000,0.000000,36067,C3386,"Montgomery, AL MSA",1132.736616,0.000000,0.003217,0,0
1,010010201002,01001020100,01001,01,AL,"Autauga County, Alabama",1307,1301,439,0.899772,0.927107,2.186788,0.239180,0.772210,0.000000,0.134396,0.004556,0.045558,0.013667,0.000000,0.000000,0.029613,0.013667,0.195900,0.166287,0.145786,0.072893,0.036446,0.093394,0.047836,0.489671,0.273145,0.081867,0.103290,0.091048,0.136190,0.071155,0.232594,0.178271,0.029074,0.068095,37.3,0.784239,0.149962,0.0,0.03443,0.031370,0.022953,62022.0,0.056618,0.136955,0.452946,32.485873,-86.489672,0.0,608.723480,0.00000,0.000000,36067,C3386,"Montgomery, AL MSA",868.606955,0.000000,0.003217,0,0
2,010010202001,01001020200,01001,01,AL,"Autauga County, Alabama",548,546,204,0.750000,0.897059,2.161765,0.200980,0.725490,0.014706,0.127451,0.000000,0.000000,0.117647,0.083333,0.063725,0.029412,0.014706,0.083333,0.063725,0.176471,0.044118,0.000000,0.181373,0.000000,0.551095,0.089416,0.129562,0.175182,0.100365,0.135036,0.109489,0.264599,0.220803,0.133212,0.180657,49.2,0.321168,0.596715,0.0,0.00000,0.082117,0.003650,58971.0,0.131387,0.171533,0.337591,32.480082,-86.474974,0.0,689.531360,0.00000,0.000000,36067,C3386,"Montgomery, AL MSA",2341.638433,0.098872,0.015046,0,0
3,010010202002,01001020200,01001,01,AL,"Autauga County, Alabama",1313,1103,340,0.805882,0.935294,1.747059,0.164706,0.826471,0.052941,0.000000,0.002941,0.055882,0.058824,0.023529,0.029412,0.026471,0.067647,0.258824,0.038235,0.155882,0.070588,0.020588,0.082353,0.055882,0.415842,0.102818,0.099772,0.317593,0.277228,0.095202,0.142422,0.231531,0.149276,0.074638,0.091394,37.2,0.380807,0.544554,0.0,0.00000,0.074638,0.000000,57063.0,0.025133,0.136329,0.211729,32.465029,-86.470777,0.0,2693.707003,0.13136,0.000000,36067,C3386,"Montgomery, AL MSA",3817.965524,0.098872,0.015046,0,0
4,010010203001,01001020300,01001,01,AL,"Autauga County, Alabama",2835,2829,1011,0.928783,0.982196,2.282888,0.023739,0.794263,0.008902,0.020772,0.004946,0.031652,0.006924,0.059347,0.046489,0.024728,0.066271,0.006924,0.117705,0.235410,0.176063,0.116716,0.051434,0.025717,0.542857,0.265608,0.077249,0.115697,0.083951,0.202822,0.092063,0.225397,0.170018,0.009524,0.063845,36.6,0.713228,0.218342,0.0,0.00388,0.064550,0.015520,84646.0,0.057143,0.097002,0.326631,32.479680,-86.460847,0.0,1899.027879,0.00589,0.002103,36067,C3386,"Montgomery, AL MSA",2339.120054,0.002005,0.007732,0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242336 entries, 0 to 242335
Data columns (total 66 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   bg_fips                                     242336 non-null  object
 1   census_tract_fips                           242336 non-null  object
 2   county_fips                                 242336 non-null  object
 3   state_fips                                  242336 non-null  object
 4   state                                       242336 non-null  object
 5   county_name                                 242336 non-null  object
 6   population                                  242336 non-null  int32
 7   non_institutionized_pop                     242336 non-null  int32
 8   households                                  242336 non-null  int32
 9   pct_hh_internet_subscription                239535 non-null  float64
 10  pct_hh_vehicle_ownership                    239535 non-null  float64
 11  avg_vehicles_per_hh                         239535 non-null  float64
 12  pct_hh_foodstamps                           239535 non-null  float64
 13  pct_home_ownership                          239535 non-null  float64
 14  pct_hh_income_up_to_10k                     239535 non-null  float64
 15  pct_hh_income_10k_to_15k                    239535 non-null  float64
 16  pct_hh_income_15k_to_20k                    239535 non-null  float64
 17  pct_hh_income_20k_to_25k                    239535 non-null  float64
 18  pct_hh_income_25k_to_30k                    239535 non-null  float64
 19  pct_hh_income_30k_to_35k                    239535 non-null  float64
 20  pct_hh_income_35k_to_40k                    239535 non-null  float64
 21  pct_hh_income_40k_to_45k                    239535 non-null  float64
 22  pct_hh_income_45k_to_50k                    239535 non-null  float64
 23  pct_hh_income_50k_to_60k                    239535 non-null  float64
 24  pct_hh_income_60k_to_75k                    239535 non-null  float64
 25  pct_hh_income_75k_to_100k                   239535 non-null  float64
 26  pct_hh_income_100k_to_125k                  239535 non-null  float64
 27  pct_hh_income_125k_to_150k                  239535 non-null  float64
 28  pct_hh_income_150k_to_200k                  239535 non-null  float64
 29  pct_hh_income_200k_and_above                239535 non-null  float64
 30  prop_female                                 240172 non-null  float64
 31  prop_age_under_18                           240172 non-null  float64
 32  prop_age_18_24                              240172 non-null  float64
 33  prop_age_18_29                              240172 non-null  float64
 34  prop_age_25_34                              240172 non-null  float64
 35  prop_age_35_44                              240172 non-null  float64
 36  prop_age_45_54                              240172 non-null  float64
 37  prop_age_50_64                              240172 non-null  float64
 38  prop_age_55_64                              240172 non-null  float64
 39  prop_age_65_69                              240172 non-null  float64
 40  prop_age_65_74                              240172 non-null  float64
 41  median_age                                  240002 non-null  float64
 42  race_pct_white                              240172 non-null  float64
 43  race_pct_african_american                   240172 non-null  float64
 44  race_pct_nativeam                           240172 non-null  float64
 45  race_pct_asian                              240172 non-null  float64
 46  race_pct_other                              242336 non-null  float64
 47  race_pct_hispanic                           240172 non-null  float64
 48  median_income                               225130 non-null  float64
 49  pct_college_enrolled                        240172 non-null  float64
 50  prop_college_educated                       240172 non-null  float64
 51  pct_married                                 240172 non-null  float64
 52  blockgroup_center_lat                       242336 non-null  float64
 53  blockgroup_center_lng                       242336 non-null  float64
 54  amindian_aknative_hawaiiannative_land_flag  242331 non-null  float64
 55  pop_density_sqmile                          242336 non-null  float64
 56  pct_inst_groupquarters_2020                 240942 non-null  float64
 57  pct_non_inst_groupquarters_2020             240942 non-null  float64
 58  zip                                         240949 non-null  object
 59  msa_code                                    224031 non-null  object
 60  MSA                                         224031 non-null  object
 61  tract_pop_density_sqmile                    241946 non-null  float64
 62  pct_tract_groupqtrs                         241401 non-null  float64
 63  pct_tract_military_employed                 241401 non-null  float64
 64  military_base_flag                          242336 non-null  int32
 65  military_base_flag_geo                      242336 non-null  int32
dtypes: float64(52), int32(5), object(9)
memory usage: 117.4+ MB

# basic dtypes

## dtype dict from .pkl file

In [3]:
with open(f"{REL_PATH}/{ACS_BG_FILENAME}.pkl", "rb") as f:
    pd_dtype_dict = pickle.load(f)

In [5]:
pd_dtype_dict

{'bg_fips': 'object',
 'census_tract_fips': 'object',
 'county_fips': 'object',
 'state_fips': 'object',
 'state': 'object',
 'county_name': 'object',
 'population': 'int32',
 'non_institutionized_pop': 'int32',
 'households': 'int32',
 'pct_hh_internet_subscription': 'float64',
 'pct_hh_vehicle_ownership': 'float64',
 'avg_vehicles_per_hh': 'float64',
 'pct_hh_foodstamps': 'float64',
 'pct_home_ownership': 'float64',
 'pct_hh_income_up_to_10k': 'float64',
 'pct_hh_income_10k_to_15k': 'float64',
 'pct_hh_income_15k_to_20k': 'float64',
 'pct_hh_income_20k_to_25k': 'float64',
 'pct_hh_income_25k_to_30k': 'float64',
 'pct_hh_income_30k_to_35k': 'float64',
 'pct_hh_income_35k_to_40k': 'float64',
 'pct_hh_income_40k_to_45k': 'float64',
 'pct_hh_income_45k_to_50k': 'float64',
 'pct_hh_income_50k_to_60k': 'float64',
 'pct_hh_income_60k_to_75k': 'float64',
 'pct_hh_income_75k_to_100k': 'float64',
 'pct_hh_income_100k_to_125k': 'float64',
 'pct_hh_income_125k_to_150k': 'float64',
 'pct_hh_income_150k_to_200k': 'float64',
 'pct_hh_income_200k_and_above': 'float64',
 'prop_female': 'float64',
 'prop_age_under_18': 'float64',
 'prop_age_18_24': 'float64',
 'prop_age_18_29': 'float64',
 'prop_age_25_34': 'float64',
 'prop_age_35_44': 'float64',
 'prop_age_45_54': 'float64',
 'prop_age_50_64': 'float64',
 'prop_age_55_64': 'float64',
 'prop_age_65_69': 'float64',
 'prop_age_65_74': 'float64',
 'median_age': 'float64',
 'race_pct_white': 'float64',
 'race_pct_african_american': 'float64',
 'race_pct_nativeam': 'float64',
 'race_pct_asian': 'float64',
 'race_pct_other': 'float64',
 'race_pct_hispanic': 'float64',
 'median_income': 'float64',
 'pct_college_enrolled': 'float64',
 'prop_college_educated': 'float64',
 'pct_married': 'float64',
 'blockgroup_center_lat': 'float64',
 'blockgroup_center_lng': 'float64',
 'amindian_aknative_hawaiiannative_land_flag': 'float64',
 'pop_density_sqmile': 'float64',
 'pct_inst_groupquarters_2020': 'float64',
 'pct_non_inst_groupquarters_2020': 'float64',
 'zip': 'object',
 'msa_code': 'object',
 'MSA': 'object',
 'tract_pop_density_sqmile': 'float64',
 'pct_tract_groupqtrs': 'float64',
 'pct_tract_military_employed': 'float64',
 'military_base_flag': 'int32',
 'military_base_flag_geo': 'int32'}

### correct

In [4]:
pd_dtype_dict['amindian_aknative_hawaiiannative_land_flag'] = 'integer'

## save .csv with dtypes

In [67]:
filename = f'{ACS_BG_FILENAME}_datatype_lookup_for_pandas.csv'

with open(filename, 'w') as f:
    w = csv.DictWriter(f, pd_dtype_dict.keys())
    w.writeheader()
    w.writerow(pd_dtype_dict)

In [68]:
check_df = pd.read_csv(filename)

In [69]:
check_df.head()

,bg_fips,census_tract_fips,county_fips,state_fips,state,county_name,population,non_institutionized_pop,households,pct_hh_internet_subscription,pct_hh_vehicle_ownership,avg_vehicles_per_hh,pct_hh_foodstamps,pct_home_ownership,pct_hh_income_up_to_10k,pct_hh_income_10k_to_15k,pct_hh_income_15k_to_20k,pct_hh_income_20k_to_25k,pct_hh_income_25k_to_30k,pct_hh_income_30k_to_35k,pct_hh_income_35k_to_40k,pct_hh_income_40k_to_45k,pct_hh_income_45k_to_50k,pct_hh_income_50k_to_60k,pct_hh_income_60k_to_75k,pct_hh_income_75k_to_100k,pct_hh_income_100k_to_125k,pct_hh_income_125k_to_150k,pct_hh_income_150k_to_200k,pct_hh_income_200k_and_above,prop_female,prop_age_under_18,prop_age_18_24,prop_age_18_29,prop_age_25_34,prop_age_35_44,prop_age_45_54,prop_age_50_64,prop_age_55_64,prop_age_65_69,prop_age_65_74,median_age,race_pct_white,race_pct_african_american,race_pct_nativeam,race_pct_asian,race_pct_other,race_pct_hispanic,median_income,pct_college_enrolled,prop_college_educated,pct_married,blockgroup_center_lat,blockgroup_center_lng,amindian_aknative_hawaiiannative_land_flag,pop_density_sqmile,pct_inst_groupquarters_2020,pct_non_inst_groupquarters_2020,zip,msa_code,MSA,tract_pop_density_sqmile,pct_tract_groupqtrs,pct_tract_military_employed,military_base_flag,military_base_flag_geo
0,object,object,object,object,object,object,int32,int32,int32,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,integer,float64,float64,float64,object,object,object,float64,float64,float64,int32,int32

In [74]:
check_dict = check_df.to_dict(orient='records')[0]

In [75]:
check_dict

{'bg_fips': 'object',
 'census_tract_fips': 'object',
 'county_fips': 'object',
 'state_fips': 'object',
 'state': 'object',
 'county_name': 'object',
 'population': 'int32',
 'non_institutionized_pop': 'int32',
 'households': 'int32',
 'pct_hh_internet_subscription': 'float64',
 'pct_hh_vehicle_ownership': 'float64',
 'avg_vehicles_per_hh': 'float64',
 'pct_hh_foodstamps': 'float64',
 'pct_home_ownership': 'float64',
 'pct_hh_income_up_to_10k': 'float64',
 'pct_hh_income_10k_to_15k': 'float64',
 'pct_hh_income_15k_to_20k': 'float64',
 'pct_hh_income_20k_to_25k': 'float64',
 'pct_hh_income_25k_to_30k': 'float64',
 'pct_hh_income_30k_to_35k': 'float64',
 'pct_hh_income_35k_to_40k': 'float64',
 'pct_hh_income_40k_to_45k': 'float64',
 'pct_hh_income_45k_to_50k': 'float64',
 'pct_hh_income_50k_to_60k': 'float64',
 'pct_hh_income_60k_to_75k': 'float64',
 'pct_hh_income_75k_to_100k': 'float64',
 'pct_hh_income_100k_to_125k': 'float64',
 'pct_hh_income_125k_to_150k': 'float64',
 'pct_hh_income_150k_to_200k': 'float64',
 'pct_hh_income_200k_and_above': 'float64',
 'prop_female': 'float64',
 'prop_age_under_18': 'float64',
 'prop_age_18_24': 'float64',
 'prop_age_18_29': 'float64',
 'prop_age_25_34': 'float64',
 'prop_age_35_44': 'float64',
 'prop_age_45_54': 'float64',
 'prop_age_50_64': 'float64',
 'prop_age_55_64': 'float64',
 'prop_age_65_69': 'float64',
 'prop_age_65_74': 'float64',
 'median_age': 'float64',
 'race_pct_white': 'float64',
 'race_pct_african_american': 'float64',
 'race_pct_nativeam': 'float64',
 'race_pct_asian': 'float64',
 'race_pct_other': 'float64',
 'race_pct_hispanic': 'float64',
 'median_income': 'float64',
 'pct_college_enrolled': 'float64',
 'prop_college_educated': 'float64',
 'pct_married': 'float64',
 'blockgroup_center_lat': 'float64',
 'blockgroup_center_lng': 'float64',
 'amindian_aknative_hawaiiannative_land_flag': 'integer',
 'pop_density_sqmile': 'float64',
 'pct_inst_groupquarters_2020': 'float64',
 'pct_non_inst_groupquarters_2020': 'float64',
 'zip': 'object',
 'msa_code': 'object',
 'MSA': 'object',
 'tract_pop_density_sqmile': 'float64',
 'pct_tract_groupqtrs': 'float64',
 'pct_tract_military_employed': 'float64',
 'military_base_flag': 'int32',
 'military_base_flag_geo': 'int32'}

Try a different format

In [ ]:
filename = f'{ACS_BG_FILENAME}_datatype_lookup_for_pandas.csv'

In [77]:
with open(filename, 'w') as f:
    w = csv.DictWriter(f, ["column", "dtype"])
    w.writeheader()
    for key, val in pd_dtype_dict.items():
        w.writerow({'column': key, 'dtype': val})

In [78]:
check_df = pd.read_csv(filename)

In [79]:
check_df.head()

              column   dtype
0            bg_fips  object
1  census_tract_fips  object
2        county_fips  object
3         state_fips  object
4              state  object

In [80]:
pd_dtype_dict

{'bg_fips': 'object',
 'census_tract_fips': 'object',
 'county_fips': 'object',
 'state_fips': 'object',
 'state': 'object',
 'county_name': 'object',
 'population': 'int32',
 'non_institutionized_pop': 'int32',
 'households': 'int32',
 'pct_hh_internet_subscription': 'float64',
 'pct_hh_vehicle_ownership': 'float64',
 'avg_vehicles_per_hh': 'float64',
 'pct_hh_foodstamps': 'float64',
 'pct_home_ownership': 'float64',
 'pct_hh_income_up_to_10k': 'float64',
 'pct_hh_income_10k_to_15k': 'float64',
 'pct_hh_income_15k_to_20k': 'float64',
 'pct_hh_income_20k_to_25k': 'float64',
 'pct_hh_income_25k_to_30k': 'float64',
 'pct_hh_income_30k_to_35k': 'float64',
 'pct_hh_income_35k_to_40k': 'float64',
 'pct_hh_income_40k_to_45k': 'float64',
 'pct_hh_income_45k_to_50k': 'float64',
 'pct_hh_income_50k_to_60k': 'float64',
 'pct_hh_income_60k_to_75k': 'float64',
 'pct_hh_income_75k_to_100k': 'float64',
 'pct_hh_income_100k_to_125k': 'float64',
 'pct_hh_income_125k_to_150k': 'float64',
 'pct_hh_income_150k_to_200k': 'float64',
 'pct_hh_income_200k_and_above': 'float64',
 'prop_female': 'float64',
 'prop_age_under_18': 'float64',
 'prop_age_18_24': 'float64',
 'prop_age_18_29': 'float64',
 'prop_age_25_34': 'float64',
 'prop_age_35_44': 'float64',
 'prop_age_45_54': 'float64',
 'prop_age_50_64': 'float64',
 'prop_age_55_64': 'float64',
 'prop_age_65_69': 'float64',
 'prop_age_65_74': 'float64',
 'median_age': 'float64',
 'race_pct_white': 'float64',
 'race_pct_african_american': 'float64',
 'race_pct_nativeam': 'float64',
 'race_pct_asian': 'float64',
 'race_pct_other': 'float64',
 'race_pct_hispanic': 'float64',
 'median_income': 'float64',
 'pct_college_enrolled': 'float64',
 'prop_college_educated': 'float64',
 'pct_married': 'float64',
 'blockgroup_center_lat': 'float64',
 'blockgroup_center_lng': 'float64',
 'amindian_aknative_hawaiiannative_land_flag': 'integer',
 'pop_density_sqmile': 'float64',
 'pct_inst_groupquarters_2020': 'float64',
 'pct_non_inst_groupquarters_2020': 'float64',
 'zip': 'object',
 'msa_code': 'object',
 'MSA': 'object',
 'tract_pop_density_sqmile': 'float64',
 'pct_tract_groupqtrs': 'float64',
 'pct_tract_military_employed': 'float64',
 'military_base_flag': 'int32',
 'military_base_flag_geo': 'int32'}

In [89]:
check_dict = {row['column']: row['dtype'] for _, row in check_df.iterrows()} #check_df.to_dict(orient='records')

In [90]:
check_dict

{'bg_fips': 'object',
 'census_tract_fips': 'object',
 'county_fips': 'object',
 'state_fips': 'object',
 'state': 'object',
 'county_name': 'object',
 'population': 'int32',
 'non_institutionized_pop': 'int32',
 'households': 'int32',
 'pct_hh_internet_subscription': 'float64',
 'pct_hh_vehicle_ownership': 'float64',
 'avg_vehicles_per_hh': 'float64',
 'pct_hh_foodstamps': 'float64',
 'pct_home_ownership': 'float64',
 'pct_hh_income_up_to_10k': 'float64',
 'pct_hh_income_10k_to_15k': 'float64',
 'pct_hh_income_15k_to_20k': 'float64',
 'pct_hh_income_20k_to_25k': 'float64',
 'pct_hh_income_25k_to_30k': 'float64',
 'pct_hh_income_30k_to_35k': 'float64',
 'pct_hh_income_35k_to_40k': 'float64',
 'pct_hh_income_40k_to_45k': 'float64',
 'pct_hh_income_45k_to_50k': 'float64',
 'pct_hh_income_50k_to_60k': 'float64',
 'pct_hh_income_60k_to_75k': 'float64',
 'pct_hh_income_75k_to_100k': 'float64',
 'pct_hh_income_100k_to_125k': 'float64',
 'pct_hh_income_125k_to_150k': 'float64',
 'pct_hh_income_150k_to_200k': 'float64',
 'pct_hh_income_200k_and_above': 'float64',
 'prop_female': 'float64',
 'prop_age_under_18': 'float64',
 'prop_age_18_24': 'float64',
 'prop_age_18_29': 'float64',
 'prop_age_25_34': 'float64',
 'prop_age_35_44': 'float64',
 'prop_age_45_54': 'float64',
 'prop_age_50_64': 'float64',
 'prop_age_55_64': 'float64',
 'prop_age_65_69': 'float64',
 'prop_age_65_74': 'float64',
 'median_age': 'float64',
 'race_pct_white': 'float64',
 'race_pct_african_american': 'float64',
 'race_pct_nativeam': 'float64',
 'race_pct_asian': 'float64',
 'race_pct_other': 'float64',
 'race_pct_hispanic': 'float64',
 'median_income': 'float64',
 'pct_college_enrolled': 'float64',
 'prop_college_educated': 'float64',
 'pct_married': 'float64',
 'blockgroup_center_lat': 'float64',
 'blockgroup_center_lng': 'float64',
 'amindian_aknative_hawaiiannative_land_flag': 'integer',
 'pop_density_sqmile': 'float64',
 'pct_inst_groupquarters_2020': 'float64',
 'pct_non_inst_groupquarters_2020': 'float64',
 'zip': 'object',
 'msa_code': 'object',
 'MSA': 'object',
 'tract_pop_density_sqmile': 'float64',
 'pct_tract_groupqtrs': 'float64',
 'pct_tract_military_employed': 'float64',
 'military_base_flag': 'int32',
 'military_base_flag_geo': 'int32'}

In [91]:
with open(filename, 'r') as f:
    reader = csv.DictReader(f)
    check_dict = {row['column']: row['dtype'] for row in reader}

In [92]:
check_dict

{'bg_fips': 'object',
 'census_tract_fips': 'object',
 'county_fips': 'object',
 'state_fips': 'object',
 'state': 'object',
 'county_name': 'object',
 'population': 'int32',
 'non_institutionized_pop': 'int32',
 'households': 'int32',
 'pct_hh_internet_subscription': 'float64',
 'pct_hh_vehicle_ownership': 'float64',
 'avg_vehicles_per_hh': 'float64',
 'pct_hh_foodstamps': 'float64',
 'pct_home_ownership': 'float64',
 'pct_hh_income_up_to_10k': 'float64',
 'pct_hh_income_10k_to_15k': 'float64',
 'pct_hh_income_15k_to_20k': 'float64',
 'pct_hh_income_20k_to_25k': 'float64',
 'pct_hh_income_25k_to_30k': 'float64',
 'pct_hh_income_30k_to_35k': 'float64',
 'pct_hh_income_35k_to_40k': 'float64',
 'pct_hh_income_40k_to_45k': 'float64',
 'pct_hh_income_45k_to_50k': 'float64',
 'pct_hh_income_50k_to_60k': 'float64',
 'pct_hh_income_60k_to_75k': 'float64',
 'pct_hh_income_75k_to_100k': 'float64',
 'pct_hh_income_100k_to_125k': 'float64',
 'pct_hh_income_125k_to_150k': 'float64',
 'pct_hh_income_150k_to_200k': 'float64',
 'pct_hh_income_200k_and_above': 'float64',
 'prop_female': 'float64',
 'prop_age_under_18': 'float64',
 'prop_age_18_24': 'float64',
 'prop_age_18_29': 'float64',
 'prop_age_25_34': 'float64',
 'prop_age_35_44': 'float64',
 'prop_age_45_54': 'float64',
 'prop_age_50_64': 'float64',
 'prop_age_55_64': 'float64',
 'prop_age_65_69': 'float64',
 'prop_age_65_74': 'float64',
 'median_age': 'float64',
 'race_pct_white': 'float64',
 'race_pct_african_american': 'float64',
 'race_pct_nativeam': 'float64',
 'race_pct_asian': 'float64',
 'race_pct_other': 'float64',
 'race_pct_hispanic': 'float64',
 'median_income': 'float64',
 'pct_college_enrolled': 'float64',
 'prop_college_educated': 'float64',
 'pct_married': 'float64',
 'blockgroup_center_lat': 'float64',
 'blockgroup_center_lng': 'float64',
 'amindian_aknative_hawaiiannative_land_flag': 'integer',
 'pop_density_sqmile': 'float64',
 'pct_inst_groupquarters_2020': 'float64',
 'pct_non_inst_groupquarters_2020': 'float64',
 'zip': 'object',
 'msa_code': 'object',
 'MSA': 'object',
 'tract_pop_density_sqmile': 'float64',
 'pct_tract_groupqtrs': 'float64',
 'pct_tract_military_employed': 'float64',
 'military_base_flag': 'int32',
 'military_base_flag_geo': 'int32'}

Easier to interpret / inspect as a file; harder to leverage / use when loading the main .csv

### final save code

In [5]:
filename = f'{ACS_BG_FILENAME}_datatype_lookup_for_pandas.csv'

In [6]:
with open(filename, 'w') as f:
    w = csv.DictWriter(f, ["column", "dtype"])
    w.writeheader()
    for key, val in pd_dtype_dict.items():
        w.writerow({'column': key, 'dtype': val})

To retrieve dict:

In [7]:
with open(filename, 'r') as f:
    reader = csv.DictReader(f)
    check_dict = {row['column']: row['dtype'] for row in reader}

In [8]:
check_dict

{'bg_fips': 'object',
 'census_tract_fips': 'object',
 'county_fips': 'object',
 'state_fips': 'object',
 'state': 'object',
 'county_name': 'object',
 'population': 'int32',
 'non_institutionized_pop': 'int32',
 'households': 'int32',
 'pct_hh_internet_subscription': 'float64',
 'pct_hh_vehicle_ownership': 'float64',
 'avg_vehicles_per_hh': 'float64',
 'pct_hh_foodstamps': 'float64',
 'pct_home_ownership': 'float64',
 'pct_hh_income_up_to_10k': 'float64',
 'pct_hh_income_10k_to_15k': 'float64',
 'pct_hh_income_15k_to_20k': 'float64',
 'pct_hh_income_20k_to_25k': 'float64',
 'pct_hh_income_25k_to_30k': 'float64',
 'pct_hh_income_30k_to_35k': 'float64',
 'pct_hh_income_35k_to_40k': 'float64',
 'pct_hh_income_40k_to_45k': 'float64',
 'pct_hh_income_45k_to_50k': 'float64',
 'pct_hh_income_50k_to_60k': 'float64',
 'pct_hh_income_60k_to_75k': 'float64',
 'pct_hh_income_75k_to_100k': 'float64',
 'pct_hh_income_100k_to_125k': 'float64',
 'pct_hh_income_125k_to_150k': 'float64',
 'pct_hh_income_150k_to_200k': 'float64',
 'pct_hh_income_200k_and_above': 'float64',
 'prop_female': 'float64',
 'prop_age_under_18': 'float64',
 'prop_age_18_24': 'float64',
 'prop_age_18_29': 'float64',
 'prop_age_25_34': 'float64',
 'prop_age_35_44': 'float64',
 'prop_age_45_54': 'float64',
 'prop_age_50_64': 'float64',
 'prop_age_55_64': 'float64',
 'prop_age_65_69': 'float64',
 'prop_age_65_74': 'float64',
 'median_age': 'float64',
 'race_pct_white': 'float64',
 'race_pct_african_american': 'float64',
 'race_pct_nativeam': 'float64',
 'race_pct_asian': 'float64',
 'race_pct_other': 'float64',
 'race_pct_hispanic': 'float64',
 'median_income': 'float64',
 'pct_college_enrolled': 'float64',
 'prop_college_educated': 'float64',
 'pct_married': 'float64',
 'blockgroup_center_lat': 'float64',
 'blockgroup_center_lng': 'float64',
 'amindian_aknative_hawaiiannative_land_flag': 'integer',
 'pop_density_sqmile': 'float64',
 'pct_inst_groupquarters_2020': 'float64',
 'pct_non_inst_groupquarters_2020': 'float64',
 'zip': 'object',
 'msa_code': 'object',
 'MSA': 'object',
 'tract_pop_density_sqmile': 'float64',
 'pct_tract_groupqtrs': 'float64',
 'pct_tract_military_employed': 'float64',
 'military_base_flag': 'int32',
 'military_base_flag_geo': 'int32'}

# DDL

## lookup pd --> DDL

In [9]:
dtype_pd_ddl_lookup = {
    'object': 'varchar(65535)',
    'float64': 'float', # same as 'DOUBLE PRECISION'. previously: #'numeric(18)',
    'int32': 'integer',
    'integer': 'integer'
}

## order data

Define order of columnso based on 2019 dataset, and logic / best judgement

In [10]:
cols_in_order = [
    'bg_fips', 'census_tract_fips', 'county_name', 'county_fips', 'state', 'state_fips',
        'msa', 'msa_code', 'zip', 'blockgroup_center_lat', 'blockgroup_center_lng', 
    'population', 'non_institutionized_pop', 'households', 'pop_density_sqmile',
       'tract_pop_density_sqmile', 
    'median_income', 'median_age',
    'prop_age_under_18', 'prop_age_18_29', 'prop_age_50_64',
       'prop_age_65_69', 'prop_age_18_24', 'prop_age_25_34', 'prop_age_35_44',
       'prop_age_45_54', 'prop_age_55_64', 'prop_age_65_74',
    'prop_female', 'pct_hh_foodstamps',
       'pct_home_ownership', 'pct_hh_vehicle_ownership', 'avg_vehicles_per_hh',
       'pct_college_enrolled', 'prop_college_educated', 'pct_married',
       'pct_tract_military_employed', 
    'race_pct_white',
       'race_pct_african_american', 'race_pct_hispanic', 'race_pct_asian',
       'race_pct_nativeam', 'race_pct_other', 
    'pct_hh_internet_subscription','pct_tract_groupqtrs',
        'amindian_aknative_hawaiiannative_land_flag', 
        'pct_inst_groupquarters_2020', 'pct_non_inst_groupquarters_2020',
        'military_base_flag', 'military_base_flag_geo',
    'pct_hh_income_up_to_10k', 'pct_hh_income_10k_to_15k',
       'pct_hh_income_15k_to_20k', 'pct_hh_income_20k_to_25k',
       'pct_hh_income_25k_to_30k', 'pct_hh_income_30k_to_35k',
       'pct_hh_income_35k_to_40k', 'pct_hh_income_40k_to_45k',
       'pct_hh_income_45k_to_50k', 'pct_hh_income_50k_to_60k',
       'pct_hh_income_60k_to_75k', 'pct_hh_income_75k_to_100k',
       'pct_hh_income_100k_to_125k', 'pct_hh_income_125k_to_150k',
       'pct_hh_income_150k_to_200k', 'pct_hh_income_200k_and_above',
                ]

In [11]:
cols_to_rename = {
    'MSA': 'msa'
}

In [12]:
# rename & order columns
df_ordered = df.rename(columns=cols_to_rename)[cols_in_order]

### save ordered data

In [13]:
df_ordered.to_csv(f'{ACS_BG_FILENAME}_for_Redshift.csv', index=False)

## create dtype dict for DDL

Tweak `pd_dtype_dict` for renamed columns

In [14]:
for old_col, new_col in cols_to_rename.items():
    col_val = pd_dtype_dict[old_col]
    del pd_dtype_dict[old_col]
    pd_dtype_dict[new_col] = col_val

In [15]:
ddl_dtype_dict = {key: dtype_pd_ddl_lookup[val] for key, val in pd_dtype_dict.items()}

In [16]:
ddl_dtype_dict

{'bg_fips': 'varchar(65535)',
 'census_tract_fips': 'varchar(65535)',
 'county_fips': 'varchar(65535)',
 'state_fips': 'varchar(65535)',
 'state': 'varchar(65535)',
 'county_name': 'varchar(65535)',
 'population': 'integer',
 'non_institutionized_pop': 'integer',
 'households': 'integer',
 'pct_hh_internet_subscription': 'float',
 'pct_hh_vehicle_ownership': 'float',
 'avg_vehicles_per_hh': 'float',
 'pct_hh_foodstamps': 'float',
 'pct_home_ownership': 'float',
 'pct_hh_income_up_to_10k': 'float',
 'pct_hh_income_10k_to_15k': 'float',
 'pct_hh_income_15k_to_20k': 'float',
 'pct_hh_income_20k_to_25k': 'float',
 'pct_hh_income_25k_to_30k': 'float',
 'pct_hh_income_30k_to_35k': 'float',
 'pct_hh_income_35k_to_40k': 'float',
 'pct_hh_income_40k_to_45k': 'float',
 'pct_hh_income_45k_to_50k': 'float',
 'pct_hh_income_50k_to_60k': 'float',
 'pct_hh_income_60k_to_75k': 'float',
 'pct_hh_income_75k_to_100k': 'float',
 'pct_hh_income_100k_to_125k': 'float',
 'pct_hh_income_125k_to_150k': 'float',
 'pct_hh_income_150k_to_200k': 'float',
 'pct_hh_income_200k_and_above': 'float',
 'prop_female': 'float',
 'prop_age_under_18': 'float',
 'prop_age_18_24': 'float',
 'prop_age_18_29': 'float',
 'prop_age_25_34': 'float',
 'prop_age_35_44': 'float',
 'prop_age_45_54': 'float',
 'prop_age_50_64': 'float',
 'prop_age_55_64': 'float',
 'prop_age_65_69': 'float',
 'prop_age_65_74': 'float',
 'median_age': 'float',
 'race_pct_white': 'float',
 'race_pct_african_american': 'float',
 'race_pct_nativeam': 'float',
 'race_pct_asian': 'float',
 'race_pct_other': 'float',
 'race_pct_hispanic': 'float',
 'median_income': 'float',
 'pct_college_enrolled': 'float',
 'prop_college_educated': 'float',
 'pct_married': 'float',
 'blockgroup_center_lat': 'float',
 'blockgroup_center_lng': 'float',
 'amindian_aknative_hawaiiannative_land_flag': 'integer',
 'pop_density_sqmile': 'float',
 'pct_inst_groupquarters_2020': 'float',
 'pct_non_inst_groupquarters_2020': 'float',
 'zip': 'varchar(65535)',
 'msa_code': 'varchar(65535)',
 'tract_pop_density_sqmile': 'float',
 'pct_tract_groupqtrs': 'float',
 'pct_tract_military_employed': 'float',
 'military_base_flag': 'integer',
 'military_base_flag_geo': 'integer',
 'msa': 'varchar(65535)'}

# We can do better

We can be more precise for some fields

## dev

In [16]:
col = 'bg_fips'
len(df.loc[0, col])

12

In [17]:
col = 'census_tract_fips'
len(df.loc[0, col])

11

In [18]:
col = 'county_fips'
len(df.loc[0, col])

5

In [19]:
col = 'state_fips'
len(df.loc[0, col])

2

In [21]:
col = 'msa_code'
len(df.loc[0, col])

5

In [25]:
df['msa_code'].sample(10)

7688      C2942
125458      NaN
21181     C3108
98782       NaN
211615    C3258
34908     C4670
143526    C1866
148483    C3562
35984     C4970
76041     C3790
Name: msa_code, dtype: object

In [ ]:
tmp = df.dropna(subset='msa_code')
tmp.reset_index(inplace=True, drop=True)

In [28]:
col = 'msa_code'
Counter([len(tmp.loc[i, col]) for i in range(len(tmp))])

Counter({5: 224031})

In [35]:
special_objects_len_dict = {
    'bg_fips': 12,
    'census_tract_fips': 11,
    'county_fips': 5,
    'state_fips': 2,
    'state': 2,
    'zip': 5,
    'msa_code': 5
}

In [33]:
# df['blockgroup_center_lat'].sample(5)

26594     33.547269
220446    40.451631
190768    39.986802
76420     40.103795
66577     21.311942
Name: blockgroup_center_lat, dtype: float64

In [40]:
special_decimal_dict = {
    'blockgroup_center_lat': 'decimal(8,6)',
    'blockgroup_center_lng': 'decimal(8,6)'
}

In [34]:
df.head()

,bg_fips,census_tract_fips,county_fips,state_fips,state,county_name,population,non_institutionized_pop,households,pct_hh_internet_subscription,pct_hh_vehicle_ownership,avg_vehicles_per_hh,pct_hh_foodstamps,pct_home_ownership,pct_hh_income_up_to_10k,pct_hh_income_10k_to_15k,pct_hh_income_15k_to_20k,pct_hh_income_20k_to_25k,pct_hh_income_25k_to_30k,pct_hh_income_30k_to_35k,pct_hh_income_35k_to_40k,pct_hh_income_40k_to_45k,pct_hh_income_45k_to_50k,pct_hh_income_50k_to_60k,pct_hh_income_60k_to_75k,pct_hh_income_75k_to_100k,pct_hh_income_100k_to_125k,pct_hh_income_125k_to_150k,pct_hh_income_150k_to_200k,pct_hh_income_200k_and_above,prop_female,prop_age_under_18,prop_age_18_24,prop_age_18_29,prop_age_25_34,prop_age_35_44,prop_age_45_54,prop_age_50_64,prop_age_55_64,prop_age_65_69,prop_age_65_74,median_age,race_pct_white,race_pct_african_american,race_pct_nativeam,race_pct_asian,race_pct_other,race_pct_hispanic,median_income,pct_college_enrolled,prop_college_educated,pct_married,blockgroup_center_lat,blockgroup_center_lng,amindian_aknative_hawaiiannative_land_flag,pop_density_sqmile,pct_inst_groupquarters_2020,pct_non_inst_groupquarters_2020,zip,msa_code,MSA,tract_pop_density_sqmile,pct_tract_groupqtrs,pct_tract_military_employed,military_base_flag,military_base_flag_geo
0,010010201001,01001020100,01001,01,AL,"Autauga County, Alabama",558,558,261,0.950192,1.000000,2.256705,0.160920,0.689655,0.000000,0.095785,0.126437,0.000000,0.068966,0.049808,0.030651,0.145594,0.000000,0.053640,0.080460,0.057471,0.030651,0.007663,0.007663,0.245211,0.460573,0.161290,0.080645,0.150538,0.173835,0.050179,0.118280,0.268817,0.159498,0.100358,0.150538,50.9,0.851254,0.021505,0.0,0.00000,0.127240,0.091398,42204.0,0.089606,0.207885,0.394265,32.465926,-86.490582,0.0,338.909937,0.00000,0.000000,36067,C3386,"Montgomery, AL MSA",1132.736616,0.000000,0.003217,0,0
1,010010201002,01001020100,01001,01,AL,"Autauga County, Alabama",1307,1301,439,0.899772,0.927107,2.186788,0.239180,0.772210,0.000000,0.134396,0.004556,0.045558,0.013667,0.000000,0.000000,0.029613,0.013667,0.195900,0.166287,0.145786,0.072893,0.036446,0.093394,0.047836,0.489671,0.273145,0.081867,0.103290,0.091048,0.136190,0.071155,0.232594,0.178271,0.029074,0.068095,37.3,0.784239,0.149962,0.0,0.03443,0.031370,0.022953,62022.0,0.056618,0.136955,0.452946,32.485873,-86.489672,0.0,608.723480,0.00000,0.000000,36067,C3386,"Montgomery, AL MSA",868.606955,0.000000,0.003217,0,0
2,010010202001,01001020200,01001,01,AL,"Autauga County, Alabama",548,546,204,0.750000,0.897059,2.161765,0.200980,0.725490,0.014706,0.127451,0.000000,0.000000,0.117647,0.083333,0.063725,0.029412,0.014706,0.083333,0.063725,0.176471,0.044118,0.000000,0.181373,0.000000,0.551095,0.089416,0.129562,0.175182,0.100365,0.135036,0.109489,0.264599,0.220803,0.133212,0.180657,49.2,0.321168,0.596715,0.0,0.00000,0.082117,0.003650,58971.0,0.131387,0.171533,0.337591,32.480082,-86.474974,0.0,689.531360,0.00000,0.000000,36067,C3386,"Montgomery, AL MSA",2341.638433,0.098872,0.015046,0,0
3,010010202002,01001020200,01001,01,AL,"Autauga County, Alabama",1313,1103,340,0.805882,0.935294,1.747059,0.164706,0.826471,0.052941,0.000000,0.002941,0.055882,0.058824,0.023529,0.029412,0.026471,0.067647,0.258824,0.038235,0.155882,0.070588,0.020588,0.082353,0.055882,0.415842,0.102818,0.099772,0.317593,0.277228,0.095202,0.142422,0.231531,0.149276,0.074638,0.091394,37.2,0.380807,0.544554,0.0,0.00000,0.074638,0.000000,57063.0,0.025133,0.136329,0.211729,32.465029,-86.470777,0.0,2693.707003,0.13136,0.000000,36067,C3386,"Montgomery, AL MSA",3817.965524,0.098872,0.015046,0,0
4,010010203001,01001020300,01001,01,AL,"Autauga County, Alabama",2835,2829,1011,0.928783,0.982196,2.282888,0.023739,0.794263,0.008902,0.020772,0.004946,0.031652,0.006924,0.059347,0.046489,0.024728,0.066271,0.006924,0.117705,0.235410,0.176063,0.116716,0.051434,0.025717,0.542857,0.265608,0.077249,0.115697,0.083951,0.202822,0.092063,0.225397,0.170018,0.009524,0.063845,36.6,0.713228,0.218342,0.0,0.00388,0.064550,0.015520,84646.0,0.057143,0.097002,0.326631,32.479680,-86.460847,0.0,1899.027879,0.00589,0.002103,36067,C3386,"Montgomery, AL MSA",2339.120054,0.002005,0.007732,0,0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242336 entries, 0 to 242335
Data columns (total 66 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   bg_fips                                     242336 non-null  object
 1   census_tract_fips                           242336 non-null  object
 2   county_fips                                 242336 non-null  object
 3   state_fips                                  242336 non-null  object
 4   state                                       242336 non-null  object
 5   county_name                                 242336 non-null  object
 6   population                                  242336 non-null  int32
 7   non_institutionized_pop                     242336 non-null  int32
 8   households                                  242336 non-null  int32
 9   pct_hh_internet_subscription                239535 non-null  float64
 10  pct_hh_vehicle_ownership                    239535 non-null  float64
 11  avg_vehicles_per_hh                         239535 non-null  float64
 12  pct_hh_foodstamps                           239535 non-null  float64
 13  pct_home_ownership                          239535 non-null  float64
 14  pct_hh_income_up_to_10k                     239535 non-null  float64
 15  pct_hh_income_10k_to_15k                    239535 non-null  float64
 16  pct_hh_income_15k_to_20k                    239535 non-null  float64
 17  pct_hh_income_20k_to_25k                    239535 non-null  float64
 18  pct_hh_income_25k_to_30k                    239535 non-null  float64
 19  pct_hh_income_30k_to_35k                    239535 non-null  float64
 20  pct_hh_income_35k_to_40k                    239535 non-null  float64
 21  pct_hh_income_40k_to_45k                    239535 non-null  float64
 22  pct_hh_income_45k_to_50k                    239535 non-null  float64
 23  pct_hh_income_50k_to_60k                    239535 non-null  float64
 24  pct_hh_income_60k_to_75k                    239535 non-null  float64
 25  pct_hh_income_75k_to_100k                   239535 non-null  float64
 26  pct_hh_income_100k_to_125k                  239535 non-null  float64
 27  pct_hh_income_125k_to_150k                  239535 non-null  float64
 28  pct_hh_income_150k_to_200k                  239535 non-null  float64
 29  pct_hh_income_200k_and_above                239535 non-null  float64
 30  prop_female                                 240172 non-null  float64
 31  prop_age_under_18                           240172 non-null  float64
 32  prop_age_18_24                              240172 non-null  float64
 33  prop_age_18_29                              240172 non-null  float64
 34  prop_age_25_34                              240172 non-null  float64
 35  prop_age_35_44                              240172 non-null  float64
 36  prop_age_45_54                              240172 non-null  float64
 37  prop_age_50_64                              240172 non-null  float64
 38  prop_age_55_64                              240172 non-null  float64
 39  prop_age_65_69                              240172 non-null  float64
 40  prop_age_65_74                              240172 non-null  float64
 41  median_age                                  240002 non-null  float64
 42  race_pct_white                              240172 non-null  float64
 43  race_pct_african_american                   240172 non-null  float64
 44  race_pct_nativeam                           240172 non-null  float64
 45  race_pct_asian                              240172 non-null  float64
 46  race_pct_other                              242336 non-null  float64
 47  race_pct_hispanic                           240172 non-null  float64
 48  median_income                               225130 non-null  float64
 49  pct_college_enrolled                        240172 non-null  float64
 50  prop_college_educated                       240172 non-null  float64
 51  pct_married                                 240172 non-null  float64
 52  blockgroup_center_lat                       242336 non-null  float64
 53  blockgroup_center_lng                       242336 non-null  float64
 54  amindian_aknative_hawaiiannative_land_flag  242331 non-null  float64
 55  pop_density_sqmile                          242336 non-null  float64
 56  pct_inst_groupquarters_2020                 240942 non-null  float64
 57  pct_non_inst_groupquarters_2020             240942 non-null  float64
 58  zip                                         240949 non-null  object
 59  msa_code                                    224031 non-null  object
 60  MSA                                         224031 non-null  object
 61  tract_pop_density_sqmile                    241946 non-null  float64
 62  pct_tract_groupqtrs                         241401 non-null  float64
 63  pct_tract_military_employed                 241401 non-null  float64
 64  military_base_flag                          242336 non-null  int32
 65  military_base_flag_geo                      242336 non-null  int32
dtypes: float64(52), int32(5), object(9)
memory usage: 117.4+ MB

In [31]:
df.columns

Index(['bg_fips', 'census_tract_fips', 'county_fips', 'state_fips', 'state',
       'county_name', 'population', 'non_institutionized_pop', 'households',
       'pct_hh_internet_subscription', 'pct_hh_vehicle_ownership',
       'avg_vehicles_per_hh', 'pct_hh_foodstamps', 'pct_home_ownership',
       'pct_hh_income_up_to_10k', 'pct_hh_income_10k_to_15k',
       'pct_hh_income_15k_to_20k', 'pct_hh_income_20k_to_25k',
       'pct_hh_income_25k_to_30k', 'pct_hh_income_30k_to_35k',
       'pct_hh_income_35k_to_40k', 'pct_hh_income_40k_to_45k',
       'pct_hh_income_45k_to_50k', 'pct_hh_income_50k_to_60k',
       'pct_hh_income_60k_to_75k', 'pct_hh_income_75k_to_100k',
       'pct_hh_income_100k_to_125k', 'pct_hh_income_125k_to_150k',
       'pct_hh_income_150k_to_200k', 'pct_hh_income_200k_and_above',
       'prop_female', 'prop_age_under_18', 'prop_age_18_24', 'prop_age_18_29',
       'prop_age_25_34', 'prop_age_35_44', 'prop_age_45_54', 'prop_age_50_64',
       'prop_age_55_64', 'prop_age_65_69', 'prop_age_65_74', 'median_age',
       'race_pct_white', 'race_pct_african_american', 'race_pct_nativeam',
       'race_pct_asian', 'race_pct_other', 'race_pct_hispanic',
       'median_income', 'pct_college_enrolled', 'prop_college_educated',
       'pct_married', 'blockgroup_center_lat', 'blockgroup_center_lng',
       'amindian_aknative_hawaiiannative_land_flag', 'pop_density_sqmile',
       'pct_inst_groupquarters_2020', 'pct_non_inst_groupquarters_2020', 'zip',
       'msa_code', 'MSA', 'tract_pop_density_sqmile', 'pct_tract_groupqtrs',
       'pct_tract_military_employed', 'military_base_flag',
       'military_base_flag_geo'],
      dtype='object')

## define, make better

In [17]:
special_objects_len_dict = {
    'bg_fips': 12,
    'census_tract_fips': 11,
    'county_fips': 5,
    'state_fips': 2,
    'state': 2,
    'zip': 5,
    'msa_code': 5
}

special_decimal_dict = {
    'blockgroup_center_lat': 'decimal(8,6)',
    'blockgroup_center_lng': 'decimal(8,6)'
}

not_null_cols = [
    'bg_fips', 'census_tract_fips', 'county_fips', 'state_fips', 'state',
       'county_name', 'blockgroup_center_lat', 'blockgroup_center_lng',
    # these are also not null, though they could be
    # 'population', 'households'
]

In [18]:
ddl_dtype_dict_better = ddl_dtype_dict.copy()

for key, val in special_objects_len_dict.items():
    ddl_dtype_dict_better[key] = f'varchar({val})'

for key, val in special_decimal_dict.items():
    ddl_dtype_dict_better[key] = val

In [19]:
ddl_dtype_dict_better

{'bg_fips': 'varchar(12)',
 'census_tract_fips': 'varchar(11)',
 'county_fips': 'varchar(5)',
 'state_fips': 'varchar(2)',
 'state': 'varchar(2)',
 'county_name': 'varchar(65535)',
 'population': 'integer',
 'non_institutionized_pop': 'integer',
 'households': 'integer',
 'pct_hh_internet_subscription': 'float',
 'pct_hh_vehicle_ownership': 'float',
 'avg_vehicles_per_hh': 'float',
 'pct_hh_foodstamps': 'float',
 'pct_home_ownership': 'float',
 'pct_hh_income_up_to_10k': 'float',
 'pct_hh_income_10k_to_15k': 'float',
 'pct_hh_income_15k_to_20k': 'float',
 'pct_hh_income_20k_to_25k': 'float',
 'pct_hh_income_25k_to_30k': 'float',
 'pct_hh_income_30k_to_35k': 'float',
 'pct_hh_income_35k_to_40k': 'float',
 'pct_hh_income_40k_to_45k': 'float',
 'pct_hh_income_45k_to_50k': 'float',
 'pct_hh_income_50k_to_60k': 'float',
 'pct_hh_income_60k_to_75k': 'float',
 'pct_hh_income_75k_to_100k': 'float',
 'pct_hh_income_100k_to_125k': 'float',
 'pct_hh_income_125k_to_150k': 'float',
 'pct_hh_income_150k_to_200k': 'float',
 'pct_hh_income_200k_and_above': 'float',
 'prop_female': 'float',
 'prop_age_under_18': 'float',
 'prop_age_18_24': 'float',
 'prop_age_18_29': 'float',
 'prop_age_25_34': 'float',
 'prop_age_35_44': 'float',
 'prop_age_45_54': 'float',
 'prop_age_50_64': 'float',
 'prop_age_55_64': 'float',
 'prop_age_65_69': 'float',
 'prop_age_65_74': 'float',
 'median_age': 'float',
 'race_pct_white': 'float',
 'race_pct_african_american': 'float',
 'race_pct_nativeam': 'float',
 'race_pct_asian': 'float',
 'race_pct_other': 'float',
 'race_pct_hispanic': 'float',
 'median_income': 'float',
 'pct_college_enrolled': 'float',
 'prop_college_educated': 'float',
 'pct_married': 'float',
 'blockgroup_center_lat': 'decimal(8,6)',
 'blockgroup_center_lng': 'decimal(8,6)',
 'amindian_aknative_hawaiiannative_land_flag': 'integer',
 'pop_density_sqmile': 'float',
 'pct_inst_groupquarters_2020': 'float',
 'pct_non_inst_groupquarters_2020': 'float',
 'zip': 'varchar(5)',
 'msa_code': 'varchar(5)',
 'tract_pop_density_sqmile': 'float',
 'pct_tract_groupqtrs': 'float',
 'pct_tract_military_employed': 'float',
 'military_base_flag': 'integer',
 'military_base_flag_geo': 'integer',
 'msa': 'varchar(65535)'}

### check

In [19]:
ddl_dtype_dict_better['amindian_aknative_hawaiiannative_land_flag']

'integer'

In [20]:
ddl_dtype_dict_better['military_base_flag_geo']

'integer'

In [23]:
ddl_dtype_dict_better['households']

'integer'

In [22]:
ddl_dtype_dict_better['prop_age_45_54']

'float'

In [21]:
ddl_dtype_dict_better['pct_non_inst_groupquarters_2020']

'float'

## save ordered dtypes

In [20]:
ddl_dtype_dict_ordered = OrderedDict()

for col in cols_in_order:
    ddl_dtype_dict_ordered[col] = ddl_dtype_dict_better[col]

In [21]:
filename = f'{ACS_BG_FILENAME}_datatype_lookup_for_sql.csv'

with open(filename, 'w') as f:
    w = csv.DictWriter(f, ["column", "dtype"])
    w.writeheader()
    for key, val in ddl_dtype_dict_better.items():
        w.writerow({'column': key, 'dtype': val})

check_df = pd.read_csv(filename)

In [22]:
check_df.head()

              column        dtype
0            bg_fips  varchar(12)
1  census_tract_fips  varchar(11)
2        county_fips   varchar(5)
3         state_fips   varchar(2)
4              state   varchar(2)

tiiight

## define DDL string

### add nulls

In [23]:
ddl_dtype_dict_for_string = ddl_dtype_dict_better.copy()

for col in not_null_cols:
    ddl_dtype_dict_for_string[col] += " not null"

In [24]:
ddl_dtype_dict_for_string

{'bg_fips': 'varchar(12) not null',
 'census_tract_fips': 'varchar(11) not null',
 'county_fips': 'varchar(5) not null',
 'state_fips': 'varchar(2) not null',
 'state': 'varchar(2) not null',
 'county_name': 'varchar(65535) not null',
 'population': 'integer',
 'non_institutionized_pop': 'integer',
 'households': 'integer',
 'pct_hh_internet_subscription': 'float',
 'pct_hh_vehicle_ownership': 'float',
 'avg_vehicles_per_hh': 'float',
 'pct_hh_foodstamps': 'float',
 'pct_home_ownership': 'float',
 'pct_hh_income_up_to_10k': 'float',
 'pct_hh_income_10k_to_15k': 'float',
 'pct_hh_income_15k_to_20k': 'float',
 'pct_hh_income_20k_to_25k': 'float',
 'pct_hh_income_25k_to_30k': 'float',
 'pct_hh_income_30k_to_35k': 'float',
 'pct_hh_income_35k_to_40k': 'float',
 'pct_hh_income_40k_to_45k': 'float',
 'pct_hh_income_45k_to_50k': 'float',
 'pct_hh_income_50k_to_60k': 'float',
 'pct_hh_income_60k_to_75k': 'float',
 'pct_hh_income_75k_to_100k': 'float',
 'pct_hh_income_100k_to_125k': 'float',
 'pct_hh_income_125k_to_150k': 'float',
 'pct_hh_income_150k_to_200k': 'float',
 'pct_hh_income_200k_and_above': 'float',
 'prop_female': 'float',
 'prop_age_under_18': 'float',
 'prop_age_18_24': 'float',
 'prop_age_18_29': 'float',
 'prop_age_25_34': 'float',
 'prop_age_35_44': 'float',
 'prop_age_45_54': 'float',
 'prop_age_50_64': 'float',
 'prop_age_55_64': 'float',
 'prop_age_65_69': 'float',
 'prop_age_65_74': 'float',
 'median_age': 'float',
 'race_pct_white': 'float',
 'race_pct_african_american': 'float',
 'race_pct_nativeam': 'float',
 'race_pct_asian': 'float',
 'race_pct_other': 'float',
 'race_pct_hispanic': 'float',
 'median_income': 'float',
 'pct_college_enrolled': 'float',
 'prop_college_educated': 'float',
 'pct_married': 'float',
 'blockgroup_center_lat': 'decimal(8,6) not null',
 'blockgroup_center_lng': 'decimal(8,6) not null',
 'amindian_aknative_hawaiiannative_land_flag': 'integer',
 'pop_density_sqmile': 'float',
 'pct_inst_groupquarters_2020': 'float',
 'pct_non_inst_groupquarters_2020': 'float',
 'zip': 'varchar(5)',
 'msa_code': 'varchar(5)',
 'tract_pop_density_sqmile': 'float',
 'pct_tract_groupqtrs': 'float',
 'pct_tract_military_employed': 'float',
 'military_base_flag': 'integer',
 'military_base_flag_geo': 'integer',
 'msa': 'varchar(65535)'}

In [25]:
ddl_create_str = ",\n".join([f"{key}   {val}" for key, val in ddl_dtype_dict_for_string.items()])

In [27]:
print(ddl_create_str)

bg_fips   varchar(12) not null,
census_tract_fips   varchar(11) not null,
county_fips   varchar(5) not null,
state_fips   varchar(2) not null,
state   varchar(2) not null,
county_name   varchar(65535) not null,
population   integer,
non_institutionized_pop   integer,
households   integer,
pct_hh_internet_subscription   float,
pct_hh_vehicle_ownership   float,
avg_vehicles_per_hh   float,
pct_hh_foodstamps   float,
pct_home_ownership   float,
pct_hh_income_up_to_10k   float,
pct_hh_income_10k_to_15k   float,
pct_hh_income_15k_to_20k   float,
pct_hh_income_20k_to_25k   float,
pct_hh_income_25k_to_30k   float,
pct_hh_income_30k_to_35k   float,
pct_hh_income_35k_to_40k   float,
pct_hh_income_40k_to_45k   float,
pct_hh_income_45k_to_50k   float,
pct_hh_income_50k_to_60k   float,
pct_hh_income_60k_to_75k   float,
pct_hh_income_75k_to_100k   float,
pct_hh_income_100k_to_125k   float,
pct_hh_income_125k_to_150k   float,
pct_hh_income_150k_to_200k   float,
pct_hh_income_200k_and_above   float,
prop_female   float,
prop_age_under_18   float,
prop_age_18_24   float,
prop_age_18_29   float,
prop_age_25_34   float,
prop_age_35_44   float,
prop_age_45_54   float,
prop_age_50_64   float,
prop_age_55_64   float,
prop_age_65_69   float,
prop_age_65_74   float,
median_age   float,
race_pct_white   float,
race_pct_african_american   float,
race_pct_nativeam   float,
race_pct_asian   float,
race_pct_other   float,
race_pct_hispanic   float,
median_income   float,
pct_college_enrolled   float,
prop_college_educated   float,
pct_married   float,
blockgroup_center_lat   decimal(8,6) not null,
blockgroup_center_lng   decimal(8,6) not null,
amindian_aknative_hawaiiannative_land_flag   integer,
pop_density_sqmile   float,
pct_inst_groupquarters_2020   float,
pct_non_inst_groupquarters_2020   float,
zip   varchar(5),
msa_code   varchar(5),
tract_pop_density_sqmile   float,
pct_tract_groupqtrs   float,
pct_tract_military_employed   float,
military_base_flag   integer,
military_base_flag_geo   integer,
msa   varchar(65535)

In [28]:
with open(f'{ACS_BG_FILENAME}_DDL_string.txt', 'w') as f:
    f.write(ddl_create_str)

## add nulls to .csv

In [32]:
ddl_dtype_list_with_nulls = []

for col, dtype in ddl_dtype_dict_better.items():
    data = [col, dtype]
    if col in not_null_cols:
        data.append("not null")
    else:
        data.append("")

    ddl_dtype_list_with_nulls.append(data)

In [33]:
ddl_dtype_list_with_nulls[:5]

[['bg_fips', 'varchar(12)', 'not null'],
 ['census_tract_fips', 'varchar(11)', 'not null'],
 ['county_fips', 'varchar(5)', 'not null'],
 ['state_fips', 'varchar(2)', 'not null'],
 ['state', 'varchar(2)', 'not null']]

In [34]:
ddl_dtype_df = pd.DataFrame(data=ddl_dtype_list_with_nulls, columns=['column', 'dtype', 'nullable'])

In [35]:
ddl_dtype_df.head()

              column        dtype  nullable
0            bg_fips  varchar(12)  not null
1  census_tract_fips  varchar(11)  not null
2        county_fips   varchar(5)  not null
3         state_fips   varchar(2)  not null
4              state   varchar(2)  not null

In [37]:
filename = f'{ACS_BG_FILENAME}_datatype_lookup_for_sql.csv'
ddl_dtype_df.to_csv(filename, index=False)